# if you want to use vault, uncomment the vars below
# if you don't set an admin password, one will be autogenerated for you
# the rest of the vars will be asked when you run tofu plan or tofu apply
# variable "vault_token" {
#   type    = string
#   default = ""
# }

# variable "vault_server" {
#   type = string
# }

variable "domain_name" {
  type = string
}

variable "ssh_pub_key" {
  type = string
}

variable "ssh_ip" {
  type = string
}

variable "admin_password" {
  type = string
  default = ""
}

variable "instance_size" {
  type = string
  default = "t3a.micro"
}
